management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: api-gateway
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

