apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: dXNlcg==        # base64 for "user"
  RABBITMQ_DEFAULT_PASS: cGFzc3dvcmQ=    # base64 for "password"
