services:
  movies_one:
    build: .
    ports:
      - "8085:8080"
    depends_on:
      - db
      - redis_cache
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/users_db
    restart: always

  movies_two:
    build: .
    ports:
      - "8086:8080"
    depends_on:
      - db
      - redis_cache
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/users_db
    restart: always

  db:
    image: postgres
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  redis_cache:
    image: redis:latest
    container_name: redisCache
    ports:
      - "6379:6379"
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisInsight
    ports:
      - "5540:5540"
    restart: always

  nginx:
    image: nginx
    ports:
      - "2727:80"
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - movies_one
      - movies_two