apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigateway-service
  template:
    metadata:
      labels:
        app: apigateway-service
    spec:
      containers:
        - name: apigateway-service
          image: loggedin213/apigateway:1.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_MAIN_WEB_APPLICATION_TYPE
              value: reactive

            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
              value: movies-service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
              value: http://movies-service:8086
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
              value: Path=/movies/**

            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_ID
              value: reviews-service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
              value: http://reviews-service:8084
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
              value: Path=/reviews/**

            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_ID
              value: users-service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_URI
              value: http://users-service:8085
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0
              value: Path=/users/**,/auth/**

            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_ID
              value: notifications-service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_URI
              value: http://notifications-service:8083
            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_PREDICATES_0
              value: Path=/notifications/**

            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: prometheus,health,info
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "true"
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS
              value: always
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION
              value: apigateway-service
