apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigateway-service
  template:
    metadata:
      labels:
        app: apigateway-service
    spec:
      containers:
        - name: apigateway-service
          image: loggedin213/apigateway:1.2
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_MAIN_WEB_APPLICATION_TYPE
              value: reactive

            # Swagger UI routes WITHOUT StripPrefix
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
              value: movies-service-swagger-ui
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
              value: http://movies-service:8086
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
              value: Path=/movies/swagger-ui.html,/movies/swagger-ui/**,/movies/webjars/**,/movies/swagger-resources/**
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0
              value: ""

            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_ID
              value: reviews-service-swagger-ui
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
              value: http://reviews-service:8084
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
              value: Path=/reviews/swagger-ui.html,/reviews/swagger-ui/**,/reviews/webjars/**,/reviews/swagger-resources/**
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_FILTERS_0
              value: ""

            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_ID
              value: users-service-swagger-ui
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_URI
              value: http://users-service:8085
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0
              value: Path=/users/swagger-ui.html,/users/swagger-ui/**,/users/webjars/**,/users/swagger-resources/**
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_FILTERS_0
              value: ""

            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_ID
              value: notifications-service-swagger-ui
            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_URI
              value: http://notifications-service:8083
            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_PREDICATES_0
              value: Path=/notifications/swagger-ui.html,/notifications/swagger-ui/**,/notifications/webjars/**,/notifications/swagger-resources/**
            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_FILTERS_0
              value: ""

            # Swagger /v3/api-docs routes WITH StripPrefix=1
            - name: SPRING_CLOUD_GATEWAY_ROUTES_4_ID
              value: movies-service-api-docs
            - name: SPRING_CLOUD_GATEWAY_ROUTES_4_URI
              value: http://movies-service:8086
            - name: SPRING_CLOUD_GATEWAY_ROUTES_4_PREDICATES_0
              value: Path=/movies/v3/api-docs
            - name: SPRING_CLOUD_GATEWAY_ROUTES_4_FILTERS_0
              value: StripPrefix=1

            - name: SPRING_CLOUD_GATEWAY_ROUTES_5_ID
              value: reviews-service-api-docs
            - name: SPRING_CLOUD_GATEWAY_ROUTES_5_URI
              value: http://reviews-service:8084
            - name: SPRING_CLOUD_GATEWAY_ROUTES_5_PREDICATES_0
              value: Path=/reviews/v3/api-docs
            - name: SPRING_CLOUD_GATEWAY_ROUTES_5_FILTERS_0
              value: StripPrefix=1

            - name: SPRING_CLOUD_GATEWAY_ROUTES_6_ID
              value: users-service-api-docs
            - name: SPRING_CLOUD_GATEWAY_ROUTES_6_URI
              value: http://users-service:8085
            - name: SPRING_CLOUD_GATEWAY_ROUTES_6_PREDICATES_0
              value: Path=/users/v3/api-docs
            - name: SPRING_CLOUD_GATEWAY_ROUTES_6_FILTERS_0
              value: StripPrefix=1

            - name: SPRING_CLOUD_GATEWAY_ROUTES_7_ID
              value: notifications-service-api-docs
            - name: SPRING_CLOUD_GATEWAY_ROUTES_7_URI
              value: http://notifications-service:8083
            - name: SPRING_CLOUD_GATEWAY_ROUTES_7_PREDICATES_0
              value: Path=/notifications/v3/api-docs
            - name: SPRING_CLOUD_GATEWAY_ROUTES_7_FILTERS_0
              value: StripPrefix=1

            # Now the general catch-all routes WITHOUT StripPrefix (as you requested)
            - name: SPRING_CLOUD_GATEWAY_ROUTES_8_ID
              value: movies-service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_8_URI
              value: http://movies-service:8086
            - name: SPRING_CLOUD_GATEWAY_ROUTES_8_PREDICATES_0
              value: Path=/movies/**

            - name: SPRING_CLOUD_GATEWAY_ROUTES_9_ID
              value: reviews-service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_9_URI
              value: http://reviews-service:8084
            - name: SPRING_CLOUD_GATEWAY_ROUTES_9_PREDICATES_0
              value: Path=/reviews/**

            - name: SPRING_CLOUD_GATEWAY_ROUTES_10_ID
              value: users-service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_10_URI
              value: http://users-service:8085
            - name: SPRING_CLOUD_GATEWAY_ROUTES_10_PREDICATES_0
              value: Path=/users/**,/auth/**

            - name: SPRING_CLOUD_GATEWAY_ROUTES_11_ID
              value: notifications-service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_11_URI
              value: http://notifications-service:8083
            - name: SPRING_CLOUD_GATEWAY_ROUTES_11_PREDICATES_0
              value: Path=/notifications/**

            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: prometheus,health,info
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "true"
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS
              value: always
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION
              value: apigateway-service

            - name: SPRINGDOC_API_DOCS_ENABLED
              value: "true"
            - name: SPRINGDOC_SWAGGER_UI_ENABLED
              value: "true"